/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GV;


import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.font.TextAttribute;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.Map;
import javax.swing.JMenuItem;

/**
 *
 * @author Anamta
 */
public class Menu extends javax.swing.JFrame {
  String v;
  String name,loc;
  Font originalFont=null;
  
    /**
     * Creates new form Menu2
     */
    public Menu() {
        initComponents();
        showDate();
        b.setVisible(false);
    select.setVisible(false);
    createMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        block = new javax.swing.JLabel();
        changeBlock = new javax.swing.JButton();
        b = new javax.swing.JComboBox<>();
        select = new javax.swing.JButton();
        logout = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        registerM = new javax.swing.JMenu();
        createTeamM = new javax.swing.JMenu();
        viewM = new javax.swing.JMenu();
        tReg = new javax.swing.JMenu();
        team = new javax.swing.JMenu();
        duesM = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 34)); // NOI18N
        jLabel1.setText("GAMING VIRTUOSO");

        welcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        welcome.setText("WELCOME");

        d.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        d.setText("date");

        block.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        block.setText("BLOCK");

        changeBlock.setText("Change Block");
        changeBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBlockActionPerformed(evt);
            }
        });

        b.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NITM Main Block", "E- Block", "Engineering College", "NIIT Old", "NIIT New", "Mall", "Univerity", " " }));

        select.setText("Select");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        logout.setText("Log Out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        registerM.setText("Register");
        registerM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMMouseClicked(evt);
            }
        });
        jMenuBar1.add(registerM);

        createTeamM.setText("Create Team");
        jMenuBar1.add(createTeamM);

        viewM.setText("View");

        tReg.setText("Registrations");
        viewM.add(tReg);

        team.setText("Teams");
        viewM.add(team);

        jMenuBar1.add(viewM);

        duesM.setText("Dues");
        duesM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duesMMouseClicked(evt);
            }
        });
        jMenuBar1.add(duesM);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(block, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(changeBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(block, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeBlock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
 public Menu(boolean flag, String n, String l)
{  
    loc=l;
    initComponents();
    b.setVisible(false);
    select.setVisible(false);
    showDate();
    initBlock(loc);
     
     name=n;
welcome.setText("Welcome, "+name);
createMenu();      
    } 
 public void createMenu()
 {
     String g;
     int t;
     try{
    Class.forName("com.mysql.jdbc.Driver");
        Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/gv","root","passcode");
       Statement smt = con.createStatement();
       String sql="select game,team from games";
       ResultSet rs=smt.executeQuery(sql);
       
       while(rs.next())
       {
         g=rs.getString("game");
         t=rs.getInt("team");        
         JMenuItem reg=new JMenuItem(g);
         tReg.add(reg);
        reg.addActionListener(new ActionListener()
                {
                     public void actionPerformed(ActionEvent e)
                 
                     {
                         
                 String name=reg.getText();
                 
                 new viewReg(name).setVisible(true);
                     }
                 
             
 
             
            });
         if(t>0)
         {   
             JMenuItem crteam=new JMenuItem(g);
             createTeamM.add(crteam);
            crteam.addActionListener(new ActionListener()
                {
                     public void actionPerformed(ActionEvent e)
                 
                     {
                         
                 String name=crteam.getText();
                 
                 new createT(name).setVisible(true);
                     }
                 
             
 
             
            });
             JMenuItem vteam=new JMenuItem(g);
             team.add(vteam);
              vteam.addActionListener(new ActionListener()
                {
                     public void actionPerformed(ActionEvent e)
                 
                     {
                         
                 String name=reg.getText();
                 
                 new viewT(name).setVisible(true);
                     }
                 
             
 
             
            });
         }
      
         
           
       }
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(this,e.getMessage());
     }
      
         
 }


  
 
 
 
 
    public void showDate()
    {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/YYY HH:mm:ss");
        Date date = new Date();
        d.setText(dateFormat.format(date));
    }
    public void initBlock(String b)
    {
        block.setText("Logged in from: "+b);
    }
    
    public void display()
    {
        this.setVisible(true);
    }
    
    
    
    
    
    
    private void registerMMouseClicked(java.awt.event.MouseEvent evt) {                                       
      gvForm g=new gvForm(loc);
      g.setVisible(true);
      
          
      
      
      
//opens registeration page
    }                                      

    private void duesMMouseClicked(java.awt.event.MouseEvent evt) {                                   

new due().setVisible(true);

    }                                  

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {                                       
int i=b.getSelectedIndex();
String block=b.getItemAt(i);
initBlock(block);

    }                                      

    private void changeBlockActionPerformed(java.awt.event.ActionEvent evt) {                                            
       b.setVisible(true);
    select.setVisible(true); 
    }                                           

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {                                    
      Font originalFont = logout.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
      logout.setFont(originalFont.deriveFont(attributes)); 
    }                                   

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {                                   
       logout.setFont(originalFont);
    }                                  

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {                                    
new Login().setVisible(true);
this.setVisible(false);

    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> b;
    private javax.swing.JLabel block;
    private javax.swing.JButton changeBlock;
    private javax.swing.JMenu createTeamM;
    private javax.swing.JLabel d;
    private javax.swing.JMenu duesM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel logout;
    private javax.swing.JMenu registerM;
    private javax.swing.JButton select;
    private javax.swing.JMenu tReg;
    private javax.swing.JMenu team;
    private javax.swing.JMenu viewM;
    private javax.swing.JLabel welcome;
    // End of variables declaration                   
}


